--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.2 (Debian 17.2-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Images; Type: TABLE; Schema: public; Owner: aragami
--

CREATE TABLE public."Images" (
    "Id" integer NOT NULL,
    "Value" bytea NOT NULL
);


ALTER TABLE public."Images" OWNER TO aragami;

--
-- Name: Images_Id_seq; Type: SEQUENCE; Schema: public; Owner: aragami
--

ALTER TABLE public."Images" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Images_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Requests; Type: TABLE; Schema: public; Owner: aragami
--

CREATE TABLE public."Requests" (
    "Id" integer NOT NULL,
    "AdminId" integer NOT NULL,
    "Address" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "DeadLine" timestamp with time zone NOT NULL,
    "PointNumber" integer NOT NULL,
    "NeededPeopleNumber" integer NOT NULL,
    "RespondedPeople" integer[] NOT NULL,
    "Description" text NOT NULL,
    "IsComplited" boolean NOT NULL,
    "IsFailed" boolean NOT NULL
);


ALTER TABLE public."Requests" OWNER TO aragami;

--
-- Name: Requests_Id_seq; Type: SEQUENCE; Schema: public; Owner: aragami
--

ALTER TABLE public."Requests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Requests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: aragami
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "Name" text NOT NULL,
    "Role" text NOT NULL,
    "Group" text NOT NULL,
    "Points" integer NOT NULL,
    "FinishedRequests" integer NOT NULL,
    "CurrentRequests" integer[] NOT NULL
);


ALTER TABLE public."Users" OWNER TO aragami;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: aragami
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Images; Type: TABLE DATA; Schema: public; Owner: aragami
--

COPY public."Images" ("Id", "Value") FROM stdin;
\.


--
-- Data for Name: Requests; Type: TABLE DATA; Schema: public; Owner: aragami
--

COPY public."Requests" ("Id", "AdminId", "Address", "Date", "DeadLine", "PointNumber", "NeededPeopleNumber", "RespondedPeople", "Description", "IsComplited", "IsFailed") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: aragami
--

COPY public."Users" ("Id", "Email", "Password", "Name", "Role", "Group", "Points", "FinishedRequests", "CurrentRequests") FROM stdin;
1	aragami@gmail.com	/OW3fQaDGZV7QZY5jyJ0Tg==	Smirnov Egor	Dev	251 PI	0	0	{}
\.


--
-- Name: Images_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: aragami
--

SELECT pg_catalog.setval('public."Images_Id_seq"', 1, false);


--
-- Name: Requests_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: aragami
--

SELECT pg_catalog.setval('public."Requests_Id_seq"', 1, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: aragami
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, true);


--
-- Name: Images PK_Images; Type: CONSTRAINT; Schema: public; Owner: aragami
--

ALTER TABLE ONLY public."Images"
    ADD CONSTRAINT "PK_Images" PRIMARY KEY ("Id");


--
-- Name: Requests PK_Requests; Type: CONSTRAINT; Schema: public; Owner: aragami
--

ALTER TABLE ONLY public."Requests"
    ADD CONSTRAINT "PK_Requests" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: aragami
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- PostgreSQL database dump complete
--

